language: node_js
services:
  - docker
node_js:
  - 8
cache:
  directories:
    - client/node_modules
    - server/node_modules
env:
  - BUILD_TARGET=client
  - BUILD_TARGET=server
script:
  - bash build/build.sh production $BUILD_TARGET
